# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import shutil
from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import QFileDialog, QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 259)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_path = QtWidgets.QLabel(self.centralwidget)
        self.main_path.setGeometry(QtCore.QRect(20, 10, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.main_path.setFont(font)
        self.main_path.setObjectName("main_path")
        self.save_path = QtWidgets.QLabel(self.centralwidget)
        self.save_path.setGeometry(QtCore.QRect(20, 90, 521, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.save_path.setFont(font)
        self.save_path.setObjectName("save_path")
        self.btn_path_main = QtWidgets.QPushButton(self.centralwidget)
        self.btn_path_main.setGeometry(QtCore.QRect(560, 50, 75, 30))
        self.btn_path_main.setObjectName("btn_path_main")
        self.btn_save_path = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_path.setGeometry(QtCore.QRect(560, 120, 75, 30))
        self.btn_save_path.setObjectName("btn_save_path")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(560, 170, 75, 30))
        self.btn_start.setObjectName("btn_start")
        self.log = QtWidgets.QLabel(self.centralwidget)
        self.log.setGeometry(QtCore.QRect(20, 180, 521, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.log.setFont(font)
        self.log.setObjectName("log")
        self.main_text_path = QtWidgets.QLineEdit(self.centralwidget)
        self.main_text_path.setGeometry(QtCore.QRect(20, 50, 530, 30))
        self.main_text_path.setText("")
        self.main_text_path.setObjectName("main_text_path")
        self.save_text_path = QtWidgets.QLineEdit(self.centralwidget)
        self.save_text_path.setGeometry(QtCore.QRect(20, 120, 530, 30))
        self.save_text_path.setText("")
        self.save_text_path.setObjectName("save_text_path")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.menu.addAction('О программе', self.creat_menu_bar)
        self.menu.addSeparator()
        # self.menu.addAction(self.action_3)
        self.menu.addAction('Выход', self.exit_win)
        self.menubar.addAction(self.menu.menuAction())
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.run()

    def run(self):
        """Запуск
        Действия каждой кнопки
        """
        self.btn_path_main.clicked.connect(self.get_path_main)
        self.btn_save_path.clicked.connect(self.get_path_save)
        self.btn_start.clicked.connect(self.btn_save_run)

    def creat_menu_bar(self):
        self.help = QMessageBox()
        self.help.setWindowTitle('Справка')
        self.help.setText("По всем вопросам обращаться \n"
                          "----maklai26rus@mail.ru----")
        self.help.exec_()

    def exit_win(self):
        MainWindow.close()

    def get_path_main(self):
        """Выбор папки от куда"""
        dirlist = QFileDialog.getExistingDirectory(self.main_text_path)
        self.main_text_path.setText(dirlist)

    def get_path_save(self):
        """Выбор папки куда"""
        dirlist = QFileDialog.getExistingDirectory(self.save_text_path)
        self.save_text_path.setText(dirlist)

    def btn_save_run(self):
        """Процесс сохранения"""
        main = os.path.exists(self.main_text_path.text())
        copy_file_path = os.path.exists(self.save_text_path.text())
        _n = 1
        if main and copy_file_path:

            try:
                for dirpath, dirnames, filnames in os.walk(self.main_text_path.text()):
                    for file in filnames:
                        full_folder = os.path.join(dirpath, file)
                        shutil.copy(full_folder, self.save_text_path.text())
                        self.log.setText(f'Скопировано {_n}')
                        _n += 1
            except:
                self.log.setText('Проверь путь ')

        else:
            self.log.setText('Проверь путь ')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.main_path.setText(_translate("MainWindow", "От куда"))
        self.save_path.setText(_translate("MainWindow", "Куда"))
        self.btn_path_main.setText(_translate("MainWindow", "..."))
        self.btn_save_path.setText(_translate("MainWindow", "..."))
        self.btn_start.setText(_translate("MainWindow", "Старт"))
        self.log.setText(_translate("MainWindow", "Лог"))
        self.menu.setTitle(_translate("MainWindow", "Справка"))
        self.action.setText(_translate("MainWindow", "О программе"))
        self.action_3.setText(_translate("MainWindow", "Выход"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
